# Generated by Django 4.1.3 on 2022-11-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='complaint',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=None, max_length=7, primary_key=True, serialize=False),
        ),
    ]
