# Generated by Django 4.1.3 on 2022-11-28 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_remove_patient_date_remove_patient_id_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_log',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
