# Generated by Django 4.1.3 on 2022-11-28 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_patient_user_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('doctor_id', models.CharField(default=None, max_length=7, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=None, max_length=8)),
                ('age', models.IntegerField(default=None)),
                ('phone_numbet', models.IntegerField(default=None)),
                ('department_code', models.CharField(max_length=7)),
                ('doctor_type', models.CharField(max_length=50)),
                ('user_log', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
