# Generated by Django 4.1.3 on 2022-11-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='phone_numbet',
            new_name='phone_number',
        ),
    ]
