# Generated by Django 4.1.3 on 2022-11-29 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_rename_phone_numbet_doctor_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.CharField(default=None, max_length=7)),
                ('drug_name', models.TextField(default=None)),
                ('drug_brand', models.TextField(default=None)),
                ('drug_ammount', models.IntegerField(default=None)),
                ('drug_discription', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='priscription',
            fields=[
                ('priscription_id', models.CharField(default=None, max_length=7, primary_key=True, serialize=False)),
                ('discription', models.TextField(default=None)),
                ('user_log', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nurse',
            fields=[
                ('nurse_id', models.CharField(default=None, max_length=7, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default=None, max_length=8)),
                ('age', models.IntegerField(default=None)),
                ('phone_number', models.IntegerField(default=None)),
                ('department_code', models.CharField(max_length=7)),
                ('doctor_type', models.CharField(max_length=50)),
                ('user_log', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_log', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
