# Generated by Django 4.1.1 on 2022-11-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_department_medication_priscription_nurse_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user_log',
        ),
        migrations.RemoveField(
            model_name='priscription',
            name='user_log',
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultant_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parient_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='priscription',
            name='doctor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='priscription',
            name='parient_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
    ]
