# Generated by Django 4.1.1 on 2022-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_patient_patient_phone_number_room_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('1', 'inpatient'), ('2', 'outpatient')], default='2', max_length=2),
        ),
    ]
