# Generated by Django 4.1.1 on 2022-12-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_doctor_type_nurse_nurse_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='condition_of_complaint',
            field=models.CharField(choices=[('1', 'normal'), ('2', 'severe'), ('3', 'extremely severe')], default='1', max_length=3),
        ),
    ]
