# Generated by Django 4.1.1 on 2022-12-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_patient_condition_of_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='parient_id',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='date_of_paymrnt',
            new_name='date_of_payment',
        ),
        migrations.RenameField(
            model_name='priscription',
            old_name='parient_id',
            new_name='patient_id',
        ),
    ]
