# Generated by Django 4.1.1 on 2022-12-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_patient_user_log_patient_assigned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_log',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user_log',
        ),
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
    ]
