# Generated by Django 4.1.1 on 2022-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_doctor_user_nurse_user_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='nurse',
            name='password',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
