# Generated by Django 4.1.1 on 2022-12-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_doctor_password_nurse_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(default=None, max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone_number',
            field=models.IntegerField(default=None, max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_phone_number',
            field=models.IntegerField(default=None, max_length=10000000000),
        ),
    ]
